#ifndef __DEF_H__
#define __DEF_H__


//#define CONN_INVALID_TIME 2000*1000*1000;
#define CONN_INVALID_TIME 60*1000*1000;

#define MAX_BASE_STATE 1000

enum CMD_ {
    CMD_RESERVE = 0,
    CMD_LOGIN = 1, //login
    CMD_GET_FRIEND = 2, //friend group
    CMD_GET_GROUPINFO = 3, //group info
    CMD_EXIT = 4,
    CMD_TEXT = 5, 
    CMD_TRANS_FILE = 6,
    CMD_SHARE_FILE = 7,
    CMD_TRANS_VIDEO = 8,
    CMD_MODIFY_INFO = 9,
    CMD_MODIFY_GROUP_INFO = 10,
    CMD_MODIFY_FRIEND = 11,
    CMD_GETALL_USERS = 12,
    CMD_FIND_USER = 13,
    CMD_ADD_FRIEND = 14,
    CMD_DEL_FRIEND = 15,
    CMD_GROUP_INFO = 16,
    CMD_TALK_INFO = 17,
    CMD_KA = 18,
    CMD_LOAD_MESSAGES = 19,
    CMD_REPORT = 20,
    CMD_SETINFO = 21,
};


enum _TEXT_TYPE_ {
    TEXT_TYPE_FRIEND = 1,
    TEXT_TYPE_GROUP = 2,
    TEXT_TYPE_TALKS = 3,
};

enum _GROUP_MEMBER_TYPE_ {
    GROUP_MEMBER_NORMAL = 0,
    GROUP_MEMBER_MANAGER = 1,
    GROUP_MEMBER_ADMIN = 2,
};

enum _GROUP_INFO_ {
    GROUP_INFO_VERIFY = 0,
    GROUP_INFO_REPLY = 1,
    GROUP_INFO_CREATE = 3,
    GROUP_INFO_MODIFY = 4,
};


#endif //__DEF_H__

